## India Today Sentiment Analysis
### Installing necessary python packages

!pip install pandas
!pip install vaderSentiment

### Importing the installed Libraries

In [1]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import pandas as pd
import re

### Reading India Today AA News Dataset and droping the missing values & some columns from the dataset.

In [2]:
data = pd.read_csv('India_Today.csv')
data = data.drop(['Headlines', 'Descriptions', 'Authors', 'Published_Dates', 'Summaries', 'Keywords'], axis=1).dropna().reset_index(drop=True)
data.head()

                                            Articles
0  Aversion therapy: effective Aversion therapy: ...
1  The original manuscript of Alcoholics Anonymou...
2  Los Angeles, Mar 10 (PTI) Demi Lovato has reca...
3  More than anything else, this letter from her ...
4  Vaccine benefits elude older women\r\n\r\n\r\n...

### cleaning each article

In [3]:
cleaning = re.compile(r"[.;:!\'?,\"()\[\]](<br\s*/><br\s*/>)|(\-)|(\/)")

data['Cleaned_Articles'] = [cleaning.sub("", data['Articles'][i].lower().replace('\r\n\r\n', ' ').replace("\'", "")) for i in range(len(data['Articles']))]

data = data.drop(['Articles'], axis=1)
data.head()

                                    Cleaned_Articles
0  aversion therapy: effective aversion therapy: ...
1  the original manuscript of alcoholics anonymou...
2  los angeles, mar 10 (pti) demi lovato has reca...
3  more than anything else, this letter from her ...
4  vaccine benefits elude older women    vitamin ...

### For each article calculating the Polarity values of the following
* Positive
* Neutral
* Negative
* Compound

In [4]:
analyser = SentimentIntensityAnalyzer()

data['polarity'] = [analyser.polarity_scores(data['Cleaned_Articles'][i]) for i in range(len(data['Cleaned_Articles']))]

In [5]:
display(data)

,Cleaned_Articles,polarity
0,aversion therapy: effective aversion therapy: ...,"{'neg': 0.093, 'neu': 0.779, 'pos': 0.128, 'co..."
1,the original manuscript of alcoholics anonymou...,"{'neg': 0.0, 'neu': 0.922, 'pos': 0.078, 'comp..."
2,"los angeles, mar 10 (pti) demi lovato has reca...","{'neg': 0.078, 'neu': 0.837, 'pos': 0.086, 'co..."
3,"more than anything else, this letter from her ...","{'neg': 0.147, 'neu': 0.796, 'pos': 0.057, 'co..."
4,vaccine benefits elude older women vitamin ...,"{'neg': 0.088, 'neu': 0.83, 'pos': 0.082, 'com..."
5,fantasy flight: model sapna kumar in a new loo...,"{'neg': 0.039, 'neu': 0.8, 'pos': 0.161, 'comp..."
6,"pour yourself your favourite drink. sit down, ...","{'neg': 0.123, 'neu': 0.814, 'pos': 0.063, 'co..."
7,"alcoholism new delhi, aug 3 (pti) in a unique ...","{'neg': 0.102, 'neu': 0.828, 'pos': 0.07, 'com..."
8,maben: back from the brink maben: back from th...,"{'neg': 0.144, 'neu': 0.803, 'pos': 0.053, 'co..."
9,london jul 10 (pti) actor simon pegg has opene...,"{'neg': 0.077, 'neu': 0.896, 'pos': 0.027, 'co..."
10,"los angeles, apr 23 (pti) rap king eminem is c...","{'neg': 0.093, 'neu': 0.828, 'pos': 0.079, 'co..."
11,definition alcohol withdrawal refers to sympto...,"{'neg': 0.154, 'neu': 0.754, 'pos': 0.092, 'co..."
12,the 33yearold married woman from chandigarh ha...,"{'neg': 0.123, 'neu': 0.805, 'pos': 0.072, 'co..."
13,"new delhi, jul 12 (pti) the indian air force (...","{'neg': 0.055, 'neu': 0.902, 'pos': 0.043, 'co..."
14,"definition alcohol use involves drinking beer,...","{'neg': 0.114, 'neu': 0.829, 'pos': 0.057, 'co..."
15,get realtime alerts and all the news on your p...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound..."
16,"definition fetal alcohol syndrome is growth, m...","{'neg': 0.123, 'neu': 0.811, 'pos': 0.067, 'co..."
17,definition pathological gambling is being unab...,"{'neg': 0.171, 'neu': 0.754, 'pos': 0.075, 'co..."
18,definition alcoholic neuropathy is damage to t...,"{'neg': 0.095, 'neu': 0.862, 'pos': 0.043, 'co..."
19,"the cover story on alcoholism (""growing malais...","{'neg': 0.137, 'neu': 0.769, 'pos': 0.094, 'co..."
20,"more than a decade ago, when i first visited t...","{'neg': 0.014, 'neu': 0.818, 'pos': 0.169, 'co..."
21,the bmc talks of opening more english medium c...,"{'neg': 0.134, 'neu': 0.803, 'pos': 0.063, 'co..."
22,goa sports and youth affairs minister ramesh t...,"{'neg': 0.018, 'neu': 0.935, 'pos': 0.048, 'co..."
23,every fifth college student in delhi drinks re...,"{'neg': 0.118, 'neu': 0.807, 'pos': 0.075, 'co..."
24,"a wellknown face on tv, he’s acted in serials ...","{'neg': 0.027, 'neu': 0.847, 'pos': 0.126, 'co..."
25,"mumbai, apr 16 (pti) wellknown television actr...","{'neg': 0.07, 'neu': 0.827, 'pos': 0.104, 'com..."
26,"by anita nair penguin in the flood of ""wimmen...","{'neg': 0.061, 'neu': 0.855, 'pos': 0.084, 'co..."
27,the sensational bust of bigtime cocaineseller ...,"{'neg': 0.123, 'neu': 0.79, 'pos': 0.088, 'com..."
28,definition substance use disorder occurs when ...,"{'neg': 0.166, 'neu': 0.744, 'pos': 0.09, 'com..."
29,"stormy crusader the people of pakistan (""storm...","{'neg': 0.112, 'neu': 0.764, 'pos': 0.124, 'co..."
30,definition drug abuse is the recurrent use of ...,"{'neg': 0.145, 'neu': 0.773, 'pos': 0.082, 'co..."
31,britney remained friends with john after their...,"{'neg': 0.141, 'neu': 0.725, 'pos': 0.135, 'co..."
32,"the 21yearold singer, who has had an onoff rel...","{'neg': 0.088, 'neu': 0.802, 'pos': 0.11, 'com..."
33,a pyrrhic victory i am anguished by the immora...,"{'neg': 0.083, 'neu': 0.795, 'pos': 0.121, 'co..."
34,"washington, aug 8 (pti) drunchies, or the desi...","{'neg': 0.025, 'neu': 0.899, 'pos': 0.077, 'co..."
35,"for people who live in the tropics, we have a ...","{'neg': 0.075, 'neu': 0.856, 'pos': 0.068, 'co..."
36,around 20 women claimed to have been raped by ...,"{'neg': 0.217, 'neu': 0.766, 'pos': 0.017, 'co..."
37,activists shout slogans outside the haryana bh...,"{'neg': 0.213, 'neu': 0.774, 'pos': 0.014, 'co..."
38,"an american cheerleader, a graduate in anthrop...","{'neg': 0.076, 'neu': 0.76, 'pos': 0.164, 'com..."
39,a catholic nun stands at the foyer of the st. ...,"{'neg': 0.132, 'neu': 0.787, 'pos': 0.081, 'co..."
40,antulay in his hospital room: back to the wall...,"{'neg': 0.097, 'neu': 0.8, 'pos': 0.103, 'comp..."
41,theres already a little hint of the impending ...,"{'neg': 0.045, 'neu': 0.817, 'pos': 0.138, 'co..."
42,few hours before the terrorism and disruptive ...,"{'neg': 0.177, 'neu': 0.774, 'pos': 0.049, 'co..."
43,"for a nation obsessed with eating, india has r...","{'neg': 0.022, 'neu': 0.873, 'pos': 0.105, 'co..."

In [6]:
data.shape

(44, 2)