## Hindustan Times Sentiment Analysis
### Installing necessary python packages

!pip install pandas
!pip install vaderSentiment

### Importing the installed Libraries

In [1]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import pandas as pd
import re

### Reading Hindustan Times AA News Dataset and droping the missing values & some columns from the dataset.

In [2]:
data = pd.read_csv('Hindustan_Times.csv')
data = data.drop(['Headlines', 'Descriptions', 'Authors', 'Published_Dates', 'Summaries', 'Keywords'], axis=1).dropna().reset_index(drop=True)
data.head()

                                            Articles
0  When a sexagenarian wobbled up to the podium a...
1  You are among people who have or had problems ...
2  He was only eight when his father handed him h...
3  Fire gives us warmth, but it also burns us. We...
4  We all like the occasional drink. Or two. Or t...

### cleaning each article

In [3]:
cleaning = re.compile(r"[.;:!\'?,\"()\[\]](<br\s*/><br\s*/>)|(\-)|(\/)")

data['Cleaned_Articles'] = [cleaning.sub("", data['Articles'][i].lower().replace('\r\n\r\n', ' ').replace("\'", "")) for i in range(len(data['Articles']))]

data = data.drop(['Articles'], axis=1)
data.head()

                                    Cleaned_Articles
0  when a sexagenarian wobbled up to the podium a...
1  you are among people who have or had problems ...
2  he was only eight when his father handed him h...
3  fire gives us warmth, but it also burns us. we...
4  we all like the occasional drink. or two. or t...

### For each article calculating the Polarity values of the following
* Positive
* Neutral
* Negative
* Compound

In [4]:
analyser = SentimentIntensityAnalyzer()

data['polarity'] = [analyser.polarity_scores(data['Cleaned_Articles'][i]) for i in range(len(data['Cleaned_Articles']))]

In [5]:
display(data)

,Cleaned_Articles,polarity
0,when a sexagenarian wobbled up to the podium a...,"{'neg': 0.059, 'neu': 0.864, 'pos': 0.077, 'co..."
1,you are among people who have or had problems ...,"{'neg': 0.081, 'neu': 0.789, 'pos': 0.13, 'com..."
2,he was only eight when his father handed him h...,"{'neg': 0.078, 'neu': 0.803, 'pos': 0.119, 'co..."
3,"fire gives us warmth, but it also burns us. we...","{'neg': 0.148, 'neu': 0.794, 'pos': 0.058, 'co..."
4,we all like the occasional drink. or two. or t...,"{'neg': 0.083, 'neu': 0.777, 'pos': 0.14, 'com..."
5,"think alcoholics, and you think of glassyeyed ...","{'neg': 0.09, 'neu': 0.842, 'pos': 0.068, 'com..."
6,"lord, grant me the strength to accept the thin...","{'neg': 0.081, 'neu': 0.8, 'pos': 0.12, 'compo..."
7,as the economic slowdown forces city executive...,"{'neg': 0.037, 'neu': 0.88, 'pos': 0.082, 'com..."
8,satyamev jayate. if you’d been watching the sh...,"{'neg': 0.115, 'neu': 0.796, 'pos': 0.088, 'co..."
9,"“hi, i’m tarun and i’m a sex addict,” said a y...","{'neg': 0.042, 'neu': 0.867, 'pos': 0.09, 'com..."
10,amy winehouse is dead and any useful understan...,"{'neg': 0.113, 'neu': 0.802, 'pos': 0.085, 'co..."
11,"a wife who drinks spirituous liquor, is of bad...","{'neg': 0.055, 'neu': 0.892, 'pos': 0.053, 'co..."
12,veteran musician phil collins says he was forc...,"{'neg': 0.072, 'neu': 0.855, 'pos': 0.073, 'co..."
13,"how odd it is, i think with a mixture of fear ...","{'neg': 0.073, 'neu': 0.843, 'pos': 0.084, 'co..."
14,lady gaga has no qualms about her former strip...,"{'neg': 0.086, 'neu': 0.82, 'pos': 0.094, 'com..."
15,former football captain vp sathyans suicide re...,"{'neg': 0.129, 'neu': 0.755, 'pos': 0.115, 'co..."
16,actor mel gibson was sentenced to three years ...,"{'neg': 0.062, 'neu': 0.893, 'pos': 0.045, 'co..."
17,consider this the sequel you never knew you we...,"{'neg': 0.037, 'neu': 0.764, 'pos': 0.199, 'co..."
18,"actor russell brand has a new tattoo, which re...","{'neg': 0.0, 'neu': 0.954, 'pos': 0.046, 'comp..."
19,staying unplugged from the rest of the world i...,"{'neg': 0.1, 'neu': 0.858, 'pos': 0.042, 'comp..."
20,"singer selena gomez, who underwent rehab in ja...","{'neg': 0.087, 'neu': 0.891, 'pos': 0.023, 'co..."
21,united nations chief ban kimoon has accused in...,"{'neg': 0.073, 'neu': 0.849, 'pos': 0.078, 'co..."
22,james bond’s alcohol consumption puts him at h...,"{'neg': 0.111, 'neu': 0.828, 'pos': 0.061, 'co..."
23,goa chief minister laxmikant parsekar has alle...,"{'neg': 0.085, 'neu': 0.849, 'pos': 0.066, 'co..."
24,the indian air force (iaf) faced the ire of th...,"{'neg': 0.061, 'neu': 0.9, 'pos': 0.039, 'comp..."
25,"in 1988, when a group of 12 men decided to org...","{'neg': 0.011, 'neu': 0.92, 'pos': 0.07, 'comp..."
26,"aashiqui 2mohit suriaditya roy kapur, shraddha...","{'neg': 0.075, 'neu': 0.745, 'pos': 0.179, 'co..."
27,"apr 20, 2019 14:05 ist terrorism is a serious ...","{'neg': 0.213, 'neu': 0.764, 'pos': 0.023, 'co..."
28,"de taali cast: riteish deshmukh, ayesha takia,...","{'neg': 0.055, 'neu': 0.744, 'pos': 0.201, 'co..."
29,britney spears is devastated after hearing the...,"{'neg': 0.094, 'neu': 0.811, 'pos': 0.095, 'co..."
30,"apr 20, 2019 14:05 ist terrorism is a serious ...","{'neg': 0.213, 'neu': 0.764, 'pos': 0.023, 'co..."
31,an important detail was revealed in the massiv...,"{'neg': 0.093, 'neu': 0.823, 'pos': 0.083, 'co..."
32,"a young woman, who was allegedly under the inf...","{'neg': 0.096, 'neu': 0.859, 'pos': 0.045, 'co..."
33,aviation regulator has asked lowcost carrier i...,"{'neg': 0.077, 'neu': 0.872, 'pos': 0.051, 'co..."
34,"dec 07, 2017 17:53 the sixth and obscured face...","{'neg': 0.21, 'neu': 0.79, 'pos': 0.0, 'compou..."
35,with the current financial year coming to an e...,"{'neg': 0.054, 'neu': 0.861, 'pos': 0.085, 'co..."
36,"feb 19, 2018 17:06 police say the victim and t...","{'neg': 0.219, 'neu': 0.781, 'pos': 0.0, 'comp..."
37,"“four crore,” he said, describing his poll exp...","{'neg': 0.039, 'neu': 0.849, 'pos': 0.112, 'co..."
38,when a 26yearold man armed with multiple guns ...,"{'neg': 0.073, 'neu': 0.895, 'pos': 0.031, 'co..."
39,the 26yearold gunman who opened fire on his fe...,"{'neg': 0.136, 'neu': 0.8, 'pos': 0.064, 'comp..."
40,a blonde girl who partied out with prince harr...,"{'neg': 0.033, 'neu': 0.835, 'pos': 0.132, 'co..."
41,actor tom sizemore was allegedly removed from ...,"{'neg': 0.063, 'neu': 0.901, 'pos': 0.035, 'co..."
42,"jan 05, 2019 13:00 married but staying in an u...","{'neg': 0.101, 'neu': 0.766, 'pos': 0.133, 'co..."
43,"feb 16, 2012 21:47 overnight raids and intensi...","{'neg': 0.137, 'neu': 0.863, 'pos': 0.0, 'comp..."
44,"mar 22, 2018 11:25 west indies captain jason h...","{'neg': 0.038, 'neu': 0.845, 'pos': 0.117, 'co..."
45,"may 28, 2013 11:34 if the internet sucks you i...","{'neg': 0.18, 'neu': 0.727, 'pos': 0.093, 'com..."
46,every single year since i moved to delhi in 20...,"{'neg': 0.124, 'neu': 0.785, 'pos': 0.091, 'co..."

In [6]:
data.shape

(47, 2)